application: jclien
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on

handlers:
- url: /favicon\.ico
  mime_type: image/png
  static_files: favicon.ico
  upload: favicon.ico

- url: /ppan\.gif
  mime_type: image/gif
  static_files: ppan.gif
  upload: ppan.gif
  
- url: .*
  script: main.py
