application: clienpad
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on

handlers:
- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /static
  static_dir: static
  
- url: .*
  script: main.py
